language: rust
rust:
  - stable
os:
  - linux
env:
  - ARCH=x86_64
  # - ARCH=i686 # TODO: Figure out how to cross compile without getting the
  # crti.so not found bug on travis
before_install:
  - sudo apt-get update
  - sudo apt-get install libasound2-dev libxrandr-dev libgtk-3-dev libc6-dev
script:
  - chmod +x ./.travis/build-release.sh
  - chmod +x ./.travis/get-features
  - ./.travis/build-release.sh
deploy:
  provider: pages
  local-dir: ./release
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # set in travis settings page
  keep-history: true
  on:
    branch: master
  
